// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Groth16 verifier for the deck-shuffle circuit. The concrete
///         implementation (Verifier.sol) is GENERATED by snarkjs from the
///         compiled circuit's proving/verification key — do not hand-write it.
///         See contracts/circuits/shuffle/.
///
///         The circuit proves: "outputDeck is a re-encryption + secret
///         permutation of inputDeck under the table public key" — without
///         revealing the permutation or the re-encryption randomness.
interface IShuffleVerifier {
    /// @param a,b,c       Groth16 proof points.
    /// @param publicInputs Hash/commitments of inputDeck, outputDeck and the
    ///         table public key (the circuit's public signals).
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata publicInputs
    ) external view returns (bool);
}

/// @notice Verifier for a single Chaum-Pedersen decryption-share proof:
///         "this partial decryption share is consistent with my published
///         public key" — so a party cannot poison a card with a bad share.
interface IDecryptShareVerifier {
    function verifyShare(
        uint256[2] calldata pk, // the prover's table key share g^sk_i
        uint256[2] calldata c0, // ciphertext component the share decrypts
        uint256[2] calldata share, // c0^sk_i
        uint256[2] calldata a, // CP proof commitment
        uint256 z // CP proof response
    ) external view returns (bool);
}
