/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SmartMoneyRouteImport } from './routes/smart-money'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CopyTradingRouteImport } from './routes/copy-trading'
import { Route as CabalsRouteImport } from './routes/cabals'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AtChar123handleChar125RouteImport } from './routes/@{$handle}'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenIdRouteImport } from './routes/token.$id'
import { Route as TSymbolRouteImport } from './routes/t.$symbol'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartMoneyRoute = SmartMoneyRouteImport.update({
  id: '/smart-money',
  path: '/smart-money',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyTradingRoute = CopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const CabalsRoute = CabalsRouteImport.update({
  id: '/cabals',
  path: '/cabals',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123handleChar125Route = AtChar123handleChar125RouteImport.update({
  id: '/@{$handle}',
  path: '/@{$handle}',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenIdRoute = TokenIdRouteImport.update({
  id: '/token/$id',
  path: '/token/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TSymbolRoute = TSymbolRouteImport.update({
  id: '/t/$symbol',
  path: '/t/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/alerts': typeof AlertsRoute
  '/cabals': typeof CabalsRoute
  '/copy-trading': typeof CopyTradingRoute
  '/feed': typeof FeedRoute
  '/inbox': typeof InboxRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/smart-money': typeof SmartMoneyRoute
  '/social': typeof SocialRoute
  '/wallet': typeof WalletRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/t/$symbol': typeof TSymbolRoute
  '/token/$id': typeof TokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/alerts': typeof AlertsRoute
  '/cabals': typeof CabalsRoute
  '/copy-trading': typeof CopyTradingRoute
  '/feed': typeof FeedRoute
  '/inbox': typeof InboxRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/smart-money': typeof SmartMoneyRoute
  '/social': typeof SocialRoute
  '/wallet': typeof WalletRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/t/$symbol': typeof TSymbolRoute
  '/token/$id': typeof TokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/alerts': typeof AlertsRoute
  '/cabals': typeof CabalsRoute
  '/copy-trading': typeof CopyTradingRoute
  '/feed': typeof FeedRoute
  '/inbox': typeof InboxRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/smart-money': typeof SmartMoneyRoute
  '/social': typeof SocialRoute
  '/wallet': typeof WalletRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/t/$symbol': typeof TSymbolRoute
  '/token/$id': typeof TokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/@{$handle}'
    | '/alerts'
    | '/cabals'
    | '/copy-trading'
    | '/feed'
    | '/inbox'
    | '/leaderboards'
    | '/rewards'
    | '/settings'
    | '/smart-money'
    | '/social'
    | '/wallet'
    | '/profile/$username'
    | '/t/$symbol'
    | '/token/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/@{$handle}'
    | '/alerts'
    | '/cabals'
    | '/copy-trading'
    | '/feed'
    | '/inbox'
    | '/leaderboards'
    | '/rewards'
    | '/settings'
    | '/smart-money'
    | '/social'
    | '/wallet'
    | '/profile/$username'
    | '/t/$symbol'
    | '/token/$id'
  id:
    | '__root__'
    | '/'
    | '/@{$handle}'
    | '/alerts'
    | '/cabals'
    | '/copy-trading'
    | '/feed'
    | '/inbox'
    | '/leaderboards'
    | '/rewards'
    | '/settings'
    | '/smart-money'
    | '/social'
    | '/wallet'
    | '/profile/$username'
    | '/t/$symbol'
    | '/token/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtChar123handleChar125Route: typeof AtChar123handleChar125Route
  AlertsRoute: typeof AlertsRoute
  CabalsRoute: typeof CabalsRoute
  CopyTradingRoute: typeof CopyTradingRoute
  FeedRoute: typeof FeedRoute
  InboxRoute: typeof InboxRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  SmartMoneyRoute: typeof SmartMoneyRoute
  SocialRoute: typeof SocialRoute
  WalletRoute: typeof WalletRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  TSymbolRoute: typeof TSymbolRoute
  TokenIdRoute: typeof TokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-money': {
      id: '/smart-money'
      path: '/smart-money'
      fullPath: '/smart-money'
      preLoaderRoute: typeof SmartMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-trading': {
      id: '/copy-trading'
      path: '/copy-trading'
      fullPath: '/copy-trading'
      preLoaderRoute: typeof CopyTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabals': {
      id: '/cabals'
      path: '/cabals'
      fullPath: '/cabals'
      preLoaderRoute: typeof CabalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}': {
      id: '/@{$handle}'
      path: '/@{$handle}'
      fullPath: '/@{$handle}'
      preLoaderRoute: typeof AtChar123handleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$id': {
      id: '/token/$id'
      path: '/token/$id'
      fullPath: '/token/$id'
      preLoaderRoute: typeof TokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$symbol': {
      id: '/t/$symbol'
      path: '/t/$symbol'
      fullPath: '/t/$symbol'
      preLoaderRoute: typeof TSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtChar123handleChar125Route: AtChar123handleChar125Route,
  AlertsRoute: AlertsRoute,
  CabalsRoute: CabalsRoute,
  CopyTradingRoute: CopyTradingRoute,
  FeedRoute: FeedRoute,
  InboxRoute: InboxRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  SmartMoneyRoute: SmartMoneyRoute,
  SocialRoute: SocialRoute,
  WalletRoute: WalletRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  TSymbolRoute: TSymbolRoute,
  TokenIdRoute: TokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
